### ISSUE TITLE
I have an issue with the life, can you help me?

### ISSUE THREAD

**Issue by lucasfernandes4472** [diasgui/comp_ufabc#1]
I would appreciate with you could help me with some questions about the source of life, mail me please.

**Comment by diasgui** [comment]
what questions?

**Comment by lucasfernandes4472** [comment]
Who gave the name of chair? What is the meaning of life?

**Comment by diasgui** [comment]
ask @murilobdio, he knows how to answer this kind of questions properly.

**Comment by lucasfernandes4472** [comment]
thanks my friend, it would be very useful for me, i keep asking myself everyday and i can't get a solution, @murilobdio hey apple

**Comment by murilobdio** [comment]
Hello hello pretty boys, probably this website https://www.etymonline.com/word/chair will help more than I can do, about the first question atleast.
Life probably doesn't have a meaning by itself, as most things in nature also doesn't have it.
Chaos and luck shall guide us all.

**Comment by diasgui** [comment]
holy guaca mole
